bind9_authoritative: yes
bind9_zones_static:
- name: sebas.tian
  type: master
- name: 30.30.172.in-addr.arpa
  type: master
bind9_slaves:
- 172.30.30.101
bind9_our_neighbors:
- 172.30.30.1
- 172.30.30.2
- 172.30.30.3
- 172.30.30.101
