# httpd/tasks/create_php_configuration.yml 

- name: Create PHP configuration file
  copy:
    content: |
      extension_dir = "/usr/local/php/lib/php/extensions/no-debug-non-zts-20200930/"
      error_reporting = E_ALL
      display_errors = On
      memory_limit = 128M
      upload_max_filesize = 2M
      post_max_size = 8M
      max_execution_time = 30
      date.timezone = "UTC"
    dest: "/usr/local/php/php.ini"
  notify: Restart Apache
