# httpd/tasks/manage_service.yml
- name: Start Apache service
  command: "/etc/init.d/apache2 start"
  async: 5
  poll: 0

- name: Ensure Apache is running
  wait_for:
    port: 80
    delay: 5
    timeout: 20
